### ISSUE TITLE
获取的消息提示为乱码

### ISSUE THREAD

**Issue by longyup** [HyDevelop/PicqBotX#15]
![image](https://user-images.githubusercontent.com/35375865/53690325-31718e80-3da3-11e9-9acf-4a9c3eb1bec7.png)
但仅限消息，昵称为中文的时候显示正常

**Comment by hykilpikonna** [comment]
启东的时候在JVM参数里加上 `-Dfile.encoding=UTF-8` 就好啦w
比如 `java -Dfile.encoding=UTF-8 -jar Build.jar`

**Comment by nitu2003** [comment]
加了 `-Dfile.encoding=UTF-8` 之后，控制台里乱码了。

**Comment by hykilpikonna** [comment]
> 加了 `-Dfile.encoding=UTF-8` 之后，控制台里乱码了。

请提供更多信息:
* 截图
* 系统和版本 (`screenfetch`)
* `java -version`
* 控制台程序
* 控制台编码
