### ISSUE TITLE
java.lang.NoClassDefFoundError: sun/reflect/Reflection

### ISSUE THREAD

**Issue by lty5240** [HyDevelop/PicqBotX#16]
Spring boot 中的异常，并且jdk 版本已降为1.8，

**Comment by hykilpikonna** [comment]
用`java -version`看看到底是什么版本嘛xx
觉得肯定是降到8没降好才出问题的...
因为Java8肯定有`sun.reflect.Reflection`这个类嘛x

**Comment by lty5240** [comment]
解决了，谢谢

**Comment by lty5240** [comment]
看文档中说明请勿使用全局变量存bot对象，那么我在定时器中的消息发送，去哪取bot

**Comment by hykilpikonna** [comment]
可以全局存啦w
只在定时任务的类里面用就可以w

不推荐全局存是因为在执行事件的时候可以获取,
如果有很多个bot对象的话,
在执行事件的时候用全局存的对象可能不是这个事件的bot对象...

然后获取`HttpApi`对象的话
因为有多账号管理,
每个账号都有单独的`HttpApi`对象...
如果要用一个不指定账号的API对象的话,
`bot.getAccountManager().getNonAccountSpecifiedApi()` 就好啦w
如果要用所有账号
`bot.getAccountManager().getAccounts()` 获取个列表,
然后循环过去就好啦w

每个`HttpApi`对象调用一次发送消息就可以了w
