### ISSUE TITLE
建议修改线程阻塞

### ISSUE THREAD

**Issue by nitu2003** [HyDevelop/PicqBotX#17]
原来不是Logger的问题，是线程被阻塞了，建议把 startBot 改为新建线程，或者添加一个不阻塞线程的方法。

**Comment by hykilpikonna** [comment]
噗噗噗w
明明线程管理要自己做的啦 (╯‵□′)╯︵┻━┻

因为大部分人都不需要多线程的吧...
所以如果默认在单独的线程启动的话
反而还要join一下好麻烦的啦xx

要异步就这样好啦 ↓

```java
new Thread(() ->
{
    try
    {
        bot.startBot();
    }
    catch (HttpServerStartFailedException e)
    {
        e.printStackTrace();
    }
}).run();
```

**Comment by hykilpikonna** [comment]
[版本v3.0.2.775](https://github.com/HyDevelop/PicqBotX/releases/tag/3.0.2.755) 已修复!
