### ISSUE TITLE
控制台乱码...

### ISSUE THREAD

**Issue by liuhulu** [HyDevelop/PicqBotX#18]
![image](https://user-images.githubusercontent.com/12758016/55275335-ac38b580-531f-11e9-9b2d-045db05ccc3a.png)

截图：👆
![image](https://user-images.githubusercontent.com/12758016/55275374-21a48600-5320-11e9-9c23-a3047b1418b7.png)

系统和版本：👆
java -version ：1.8.0.181
控制台程序：UTF-8
控制台编码: UTF-8

CODE :

>
 		PicqConfig config = new PicqConfig(8080);
		PicqBotX bot = new PicqBotX(config);
		bot.addAccount("Bot01", "127.0.0.1", 5700);
		bot.getEventManager().registerListeners(new TestCase());
		bot.startBot();

**Comment by liuhulu** [comment]
补充mvm配置

> 
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.encoding>UTF-8</maven.compiler.encoding>
	</properties>

**Comment by hykilpikonna** [comment]
这个是因为 Eclipse 控制台不支持 `Xterm256` 颜色码...
推荐换 [IntelliJ IDEA](https://www.jetbrains.com/idea/) 嗯w
( 才不是广告哈哈哈哈哈哈
<br>

### 选项 1. 关掉颜色
`bot.getConfig().setColorSupportLevel(ColorSupportLevel.DISABLED);`
这样就好啦w
( 必须在`bot.startBot()`之前调用w
不过不推荐w
毕竟没有颜色就不好看了嘛 (╯‵□′)╯︵┻━┻
<br>

### 选项 2. Eclipse 颜色插件
或者可以试试颜色插件啦w
详细介绍: https://mihai-nita.net/2013/06/03/eclipse-plugin-ansi-in-console/
源码栈: https://github.com/mihnita/ansi-econsole
( 还是 [IntelliJ IDEA](https://www.jetbrains.com/idea/) 好用w
