### ISSUE TITLE
控制台无法输出颜色，表现为乱码

### ISSUE THREAD

**Issue by longyup** [HyDevelop/PicqBotX#20]
1. 控制台无法输出颜色，表现为乱码
![image](https://user-images.githubusercontent.com/35375865/57562803-9d3a2e00-73c8-11e9-88ae-a830f813737c.png)

在win10 1803以及Windows Server2008r2均有出现
而在idea能够正常显示

2. 在Server2008r2的cmd中中文显示为乱码，而在powershell表现正常
 java -version ：1.8.0.181
控制台程序：UTF-8
控制台编码: UTF-8  
启动命令已配置了-Dfile.encoding=UTF-8

**Comment by hykilpikonna** [comment]
在`new PicqBotX(config)`之前设置一下
`config.setColorSupportLevel(ColorSupportLevel.OS_DEPENDENT)`就好啦w
这样如果是Windows就只输出预设颜色了w
会移除RGB颜色w
( 默认是`ColorSupportLevel.FORCED`嗯x

( 明明是微软的Bug (╯‵□′)╯︵┻━┻
( 2019了还不支持xterm-256哇xx
( 快给微软发个Feature Request嗯xx
