### ISSUE TITLE
[Bug] cc.moecraft.icq.command.interfaces.GroupCommand无法正确执行

### ISSUE THREAD

**Issue by finalriod** [HyDevelop/PicqBotX#26]
**介绍这个 Bug:**
这个BUG具体原因是GroupUserManager中的groupCache调用containsKey()方法时传入的参数有问题, 导致GroupCommand无法正确被执行

**这个 Bug 是怎样出现的?**
新建一个类实现GroupCommand接口, 但groupMessage方法无法正确被CommandManager调用

**没有 Bug 的话应该是什么样子的?**
群消息发送后应正确被CommandManager调用, 从而进入对应的groupMessage方法, 继而执行相应业务逻辑

**截图:**
![EH8QU1VC9(AB VE6YT@GJ$1](https://user-images.githubusercontent.com/25916604/71400943-446f8b00-2663-11ea-9769-2fc8a494505f.png)

**PicqBotX 运行环境:**
 - 系统: Windows 10 1903
 - 版本: 4.12.0.1015.PRE

**CoolQ HTTP 运行环境:**
 - 系统: Windows 10 1903
 - 酷Q 版本: 5.15.5
 - HTTP 插件版本: 4.12.3

**PicqBotX 配置:**
```
{
  "debug": false,
  "noVerify": false,
  "useAsyncCommands": true,
  "maintenanceMode": false,
  "maintenanceResponse": "- 机器人正在维护 -",
  "autoMultiAccountOptimizations": true,
  "multiAccountOptimizations": true,
  "eventPaused": false,
  "httpPaused": false,
  "apiRateLimited": false,
  "apiAsync": false,
  "commandArgsSplitRegex": " ",
  "colorSupportLevel": "FORCED",
  "logPath": "",
  "logFileName": "PicqBotX-Log",
  "logInit": false,
  "commandErrorHandler": {}
}
```

**Comment by hykilpikonna** [comment]
修复啦w
谢谢w
