### ISSUE TITLE
IDEA输出乱码

### ISSUE THREAD

**Issue by xiaoyvyv** [HyDevelop/PicqBotX#27]
![图片](https://user-images.githubusercontent.com/29088158/71424559-a369ea00-26cd-11ea-8114-a719d813e1f0.png)

**Comment by xiaoyvyv** [comment]
IDEA输出乱码

**Comment by hykilpikonna** [comment]
以后请认真填写 issue 模板哇 (╯‵□′)╯︵┻━┻

既然没有填就请回答以下问题w

1. 你是什么系统?
2. 系统默认编码是什么? (Powershell: `[System.Text.Encoding]::Default`)
3. `Settings → File Encoding → Project Encoding → IDE Encoding` 这里显示的编码是什么?
4. 试试在启动脚本里面加 `-Dfile.encoding=UTF-8`

**Comment by hykilpikonna** [comment]
太久没回复关掉了w

**Comment by FhrShadow** [comment]
如果你和我一样遇到这个问题，并尝试了上面大佬给出的方法没用而又恰巧使用了gradle来构建项目的话，那么试着在build.gradle里面加上
```
tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
```
