### ISSUE TITLE
在某些时候命令无法被执行

### ISSUE THREAD

**Issue by StarWishsama** [HyDevelop/PicqBotX#28]
**介绍这个 Bug:**
请写清楚这个 Bug 有什么问题什么的w
有些时候命令无法执行，HTTP API显示代码204

**这个 Bug 是怎样出现的?**
开发者怎样才能重现这个 Bug?
[有问题的代码](https://github.com/StarWishsama/Nameless-Bot/blob/http-api/src/main/java/io/github/starwishsama/namelessbot/commands/InfoCommand.java) 

**没有 Bug 的话应该是什么样子的?**
如果它正确的执行了会怎样呢w?
正常执行命令

**截图:**
请放一点截图w
无

**PicqBotX 运行环境:**
 - 系统: Windows Server 2012 R2 Datacenter
 - 版本: 4.12.0.1015.PRE

**CoolQ HTTP 运行环境:**
 - 系统: Windows Server 2012 R2 Datacenter
 - 酷Q 版本: 5.15.5A
 - HTTP 插件版本: 4.12.3

**PicqBotX 配置:**
.setUseAsyncCommands(true)
.setColorSupportLevel(ColorSupportLevel.OS_DEPENDENT)
.setDebug(true)

**Comment by hykilpikonna** [comment]
204 就是成功呀x
https://cqhttp.cc/docs/4.12/#/Post
这里写了所有上报相应都要是 204...
我没办法重现这个 Bug,
觉得可能是 `isCoolDown` 的问题啦w
在第一个 `if` 外面加输出看看是不是每次都能执行到w
( 甩锅w

**Comment by StarWishsama** [comment]
还是之前那段代码的链接 已经把i isCooldown去掉了 还是不能用（
别的命令就正常

![IMG_20191229_104857](https://user-images.githubusercontent.com/25561848/71551724-eeb32e00-2a28-11ea-9230-6c08ae78276a.jpg)
![IMG_20191229_104846](https://user-images.githubusercontent.com/25561848/71551725-ef4bc480-2a28-11ea-9bfc-33775098bd9c.jpg)

**Comment by StarWishsama** [comment]
试了下 test 里面的异常监听器, 请问为什么会获取不到用户的 QQ 号呢?
![Snapshot](https://i.loli.net/2019/12/29/YpXi6VG3Kc18R5m.png)

**Comment by hykilpikonna** [comment]
更新 https://github.com/HyDevelop/PicqBotX/releases/tag/4.12.0.1019.PRE
