### ISSUE TITLE
本地时间监听器正常，打jar后上到服务端，监听器失效？？

### ISSUE THREAD

**Issue by CuberWRG** [HyDevelop/PicqBotX#29]
本地时间监听器正常，打jar后上到服务端，监听器失效？？

**Comment by CuberWRG** [comment]
PicqBotX版本：4.12.0.1019.PRE
SpringBoot版本：2.0.8.RELEASE

**Comment by CuberWRG** [comment]
本地运行jar包（Win10），监听器是没问题的，但是放到服务器(Linux)，监听器就不起作用了

**Comment by hykilpikonna** [comment]
对不起一直没看到...
觉得应该是 Docker 端口映射错了w
但是服务器的问题可以去群里问w
因为支持 Linux 运行所以和 PicqBotX 无关啦w
