### ISSUE TITLE
Feature: Exception自动上报

### ISSUE THREAD

**Issue by nitu2003** [HyDevelop/PicqBotX#36]
简单来讲就是在执行指令的时候出现的RuntimeException不会有任何上报，除错会比较麻烦。
希望可以添加一个Exception自动上报，无论是printStacktrace还是根据event上报。
并且在config中可以关闭这个功能。

本来想自己写的，但是关于指令的部分太乱了，怕改的不对，就发issue了。w

**Comment by hykilpikonna** [comment]
啊我好懒w
;-;

**Comment by nitu2003** [comment]
~~不能懒呐，小桂！~~
