### ISSUE TITLE
最新版本监听器失效

### ISSUE THREAD

**Issue by CuberWRG** [HyDevelop/PicqBotX#37]
目前使用最新版本4.12.0.1019.PRE，监听器失效，没有办法监听到任何事件

**Comment by hykilpikonna** [comment]
( 给了模板都不认真填模板嘛w?! (╯‵□′)╯︵┻━┻

![image](https://user-images.githubusercontent.com/22280294/75835083-e6aa9e00-5d8b-11ea-9faf-fc3d0f45befa.png)

只说"监听器失效"的话只有神能帮你啦w
毕竟别人没有这样的问题w

至少截图下 Main 方法嘛w
截图下 PicqBotX 传入的端口设置, 还有 CQHTTP 的端口设置w
或者可以去群里问w (498386389)

**Comment by CuberWRG** [comment]
作者大大我错了

**Comment by hykilpikonna** [comment]
啊什么鬼啦w
解决了嘛w?
