### ISSUE TITLE
需要帮助: 如何关闭机器人

### ISSUE THREAD

**Issue by czp3009** [HyDevelop/PicqBotX#38]
众所周知, `bot.startBot();` 可以启动一个机器人.

而它内部会调用 `HttpServer.start`, 但是 httpServer 实例被 protected 修饰在 `cc.moecraft.icq.receiver.PicqHttpServer`中.

那么问题来了, 如何关闭它(不是指关闭整个进程).

**Comment by hykilpikonna** [comment]
为什么要不关掉进程的同时完全关掉 http server 呢w
停止 http 接收的话可以 `bot.getConfig().setHttpPaused(true)`
而且其实 jetty server 有 getter 的啦

**Comment by czp3009** [comment]
因为需要制作一个 重载配置 文件的功能, 所以需要关闭上一个创建的机器人然后创建根据新的配置产生的机器人. 所以上一个机器人得彻底关闭(不然就内存泄露了)

**Comment by hykilpikonna** [comment]
那就 `bot.getHttpServer().getServer()` 关掉吧w

**Comment by czp3009** [comment]
.......

突然意识到, kotlin 写多了, 忘记了 getter
