### ISSUE TITLE
[Bug] maven中心库只能查找到4.12.0.1019.PRE版本的picq

### ISSUE THREAD

**Issue by MIK08** [HyDevelop/PicqBotX#46]
![JUF 0P@O R49DIV4T@SZ4I7](https://user-images.githubusercontent.com/53412819/88285680-1e59b880-cd22-11ea-88ce-1576dcb4cd94.png)
4.15.0.1058版本无法在中心库中找到, 
![image](https://user-images.githubusercontent.com/53412819/88285744-35000f80-cd22-11ea-9cd9-ccbb3d08da9b.png)
只有4.12.0.1019.PRE版本才能找到
希望大大能在github上传一下库
qwq本人萌新, 可能说的有点问题

**Comment by hykilpikonna** [comment]
因为根本就没有传到中心库上呀w
现在还在 Jitpack 库里面啦w
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
